### PR TITLE
update python to 3.4 and go to 1.4.2 and fix a path in the README

### PR DESCRIPTION
**Pull request by kimhmadsen**

### CODE REVIEW

**Comment by twolfson** [comment]
Ah cool. I see the updates in the wiki:

https://github.com/limetext/lime/wiki/Building-on-Ubuntu-14.04

I will take a look at this shortly.

**Comment by twolfson** [comment]
When I run `./termbox`, I am receiving:

```
./termbox: error while loading shared libraries: libpython3.3m.so.1.0: cannot open shared object file: No such file or directory
```

Can you take a look at that?

**Comment by kimhmadsen** [comment]
I can't see that error? is it in the log file or on the terminal? This is my first use of lime maybe I have missed?
I only see the this "No clipboard utilities available. Please install xsel or xclip." Should we add this?

**Comment by twolfson** [comment]
I was having some internet issues when provisioning but Vagrant seemed to exit fine. I will try again later this week.

**Comment by twolfson** [comment]
As for `xsel`/`xclip`, I am not sure how well those play with an SSH connection. This was mostly for previewing `lime` without installing `go` to the host system.

**Comment by twolfson** [comment]
Yep, still getting the same error. Can you verify that your `precise64` image is from the proper `box_url`?

```
$ vagrant box list
precise64       (virtualbox, 0)
```

**Comment by twolfson** [comment]
If that is up to par, I am tempted to upgrade to `ubuntu/trusty64` and relocate all provisioning into a single `bootstrap.sh` file since there could be misconfigurations like `set -x`.

**Comment by kimhmadsen** [comment]
Yes, I'm using that vagrant box. 

    Kims-MacBook-Pro:vagrant-lime kim$ vagrant box list
    precise64 (virtualbox, 0)

**Comment by twolfson** [comment]
Can you destroy and reprovision your box as a sanity check?

```bash
vagrant destroy --force
vagrant up
```

**Comment by kimhmadsen** [comment]
I have done

    vagrant box remove precise64
    vagrant destroy -f 
    rm -rf code

    vagrant up
    vagrant ssh
    cd /vagrant/code/go/src/github.com/limetext/lime/frontend/termbox/
    ./termbox

Have you remembered to `rm -rf code`?

**Comment by twolfson** [comment]
Derp, that's probably the problem. I will take try that out later this week.

**Comment by twolfson** [comment]
Alright, removed `code` and got it running. Landing the PR now.

**Comment by twolfson** [comment]
This has been landed and released in `1.1.0`. Thanks for the PR!

**Pull request merged**
