### PR TITLE
Adding required vagrant plugins to Vagrantfile

### PR DESCRIPTION
**Pull request by qbarbosa**
This PR aims to solve the issue #3

### CODE REVIEW

**Comment by twolfson** [comment]
I think the issue in #3 is specific to OS X. I don't think it's reasonable to make this a catch-all solution. We could link to the issue in the README though with the corresponding error text

**Comment by qbarbosa** [comment]
Oh I thought that plugin was required for every OS, my bad.

We could add an OS detection around this chunk of code though :
```
if (Vagrant::Util::Platform.mac?) {
  ...
}
```

**Comment by twolfson** [comment]
I guess my hesitation at installing a plugin is that this repo aims to self-contain the `lime` install process but we are installing something system wide to do so. Hence my suggestion for a README note =/

**Comment by qbarbosa** [comment]
Oh ok I understand your logic!

**Pull request closed without merging**
